# Generated by Django 4.1.5 on 2023-01-12 16:56

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=255, verbose_name='СЕО-заголовок страницы')),
                ('seo_description', models.TextField(blank=True, verbose_name='СЕО-описание страницы')),
                ('policy', ckeditor.fields.RichTextField(blank=True, verbose_name='Политика конфиденциальности')),
            ],
            options={
                'verbose_name': 'Глобальные настройки',
            },
        ),
    ]
